# Generated by Django 5.0.7 on 2026-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='payment',
            field=models.CharField(choices=[('card', 'Оплата картой МИР'), ('transfer', 'Предоплата по QR-коду'), ('installment', 'Постоплата в офисе организации')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
